dist: xenial
language: java

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U -P jdeps
 
cache:
  directories:
  - $HOME/.m2

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      jdk: openjdk8
      script:
        - mvn test -B -P coverage
    - stage: test
      jdk: oraclejdk11
      script:
        - mvn test -B
    - stage: test
      jdk: openjdk11
      script:
        - mvn test -B
    